# Generated by Django 3.0.3 on 2020-04-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infected',
            name='radius',
        ),
        migrations.AddField(
            model_name='infected',
            name='District',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='infected',
            name='State',
            field=models.CharField(default='India', max_length=255),
        ),
        migrations.AddField(
            model_name='infected',
            name='corona',
            field=models.IntegerField(default=0),
        ),
    ]
